site_name: "Yirgacheffe"
site_url: "https://yirgacheffe.org"

theme:
  name: "material"
  logo: "assets/yirgacheffe-min.svg"
  primary: "#065f65"
  features:
    - header.autohide: false
    - navigation.instant: true

extra_css:
  - css/extra.css

plugins:
- search
- mkdocstrings
- gen-files:
    scripts:
    - docs/gen_changelog.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - API reference:
    - Core: api/core.md
    - Expressions: api/expressions.md
    - Operators: api/operators.md
    - Classes:
      - Area: api/classes/area.md
      - MapProjection: api/classes/mapprojection.md
      - Window: api/classes/window.md
    - Enums:
      - DataType: api/enums/datatype.md
  - Code of conduct: CODE_OF_CONDUCT.md
  - Changelog: changelog.md
